Documentation:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/*.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/*.rb"
    - "spec/**/*.rb"

Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/FileName:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Lambda:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false


AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'lib/tasks/*'
    - 'app/models/concerns/searchable.rb'
    - 'test/test_helper.rb'
    - 'app/services/tag_filter.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/utilities.rb'
