Documentation:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/*.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/*.rb"
    - "spec/**/*.rb"

Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 5
Metrics/ParameterLists:
  Max: 4

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
