db:
  image: postgres:9.4.4
  ports:
    - "5432"

web:
  build: .
  command: bundle exec unicorn -p 3000 -c config/unicorn.rb
  volumes:
    - .:/speakerinnen-liste
  ports:
    - "3000:3000"
  links:
    - db

