# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7ba3436266d1861b97d79361f2451d6cf56608e00d3191a2ec5a45c0c00f301d5062a5ad67dfde3318e91b81cf6482d1d4e2f535c7f57fce6a598cb7eecbabe

test:
  secret_key_base: e56d3a2e888c2a8c66eca864867d2d875572fd35cdeca0d9529ad5f11357e76b4631313d365e0f4666f4d8ef63816c31b7c2b6b4d4153504d767f1d9005b578b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
