rvm:
 - 1.8.7
 - 1.9.2
 - 1.9.3
 - ree
 - jruby
 - rbx
script: bundle exec rake test
notifications:
  email: false
  campfire:
    secure: "CGWvthGkBKNnTnk9YSmf9AXKoiRI33fCl5D3jU4nx3cOPu6kv2R9nMjt9EAo\nOuS4Q85qNSf4VNQ2cUPNiNYSWQ+XiTfivKvDUw/QW9r1FejYyeWarMsSBWA+\n0fADjF1M2dkDIVLgYPfwoXEv7l+j654F1KLKB69F0F/netwP9CQ="
